services:
  postgres:
    image: postgres:17.5-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pa55word
      POSTGRES_USER: greenlight
      POSTGRES_DB: greenlight
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
volumes:
  postgres_data:
